storage:
  node:
    id: ${app.nodeId}
  file-system:
    base-path: ./data

spring:
  datasource:
    username: ${app.dbUsername}
    password: ${app.dbPassword}
    url: jdbc:mysql://${app.dbHost}:3306/dfs?useUnicode=true&characterEncoding=utf-8&useSSL=false